theme: jekyll-theme-Modernist  # Example theme, you can change this to your preferred theme
# https://github.com/pages-themes/modernist     
#
#    Architect
#    Cayman
#    Dinky
#    Hacker
#    Leap day
#    Merlot
#    Midnight
#    Minima
#    Minimal
#    Modernist
#    Slate
#    Tactile
#    Time machine
